# Generated by Django 5.1.4 on 2024-12-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='image',
        ),
        migrations.AddField(
            model_name='floor',
            name='svg',
            field=models.FileField(default=1, upload_to='floor_svgs/'),
            preserve_default=False,
        ),
    ]
